import KPI_Table_Interface from "./interface.mjs";

/* ["average_alarm_time",
"average_alarm_time_past",
"average_idle_time",
"average_idle_time_past",
"average_power_consumption",
"average_power_consumption_idle_state",
"average_power_consumption_wk_state",
"average_wk_time",
"average_wk_time_past",
"estimate_tot_cost",
"highest_alarm_time_trend",
"highest_alarm_time_trend_machine_id",
"highest_power_consumption",
"highest_power_consumption_idle_state_machine_cost",
"highest_power_consumption_idle_state_machine_id",
"highest_power_consumption_idle_state_machine_tot_value",
"highest_power_consumption_idle_state_machine_value_per_hour",
"highest_power_consumption_machine_id",
"highest_power_consumption_wk_state_machine_cost",
"highest_power_consumption_wk_state_machine_id",
"highest_power_consumption_wk_state_machine_tot_value",
"highest_power_consumption_wk_state_machine_value_per_hour",
"highest_variability_wk_time",
"least_used_machine_id",
"least_used_machine_time",
"longest_alarm_time",
"longest_alarm_time_machine_id",
"lowest_alarm_time_trend",
"lowest_alarm_time_trend_machine_id",
"lowest_power_consumption",
"lowest_power_consumption_idle_state_machine_cost",
"lowest_power_consumption_idle_state_machine_id",
"lowest_power_consumption_idle_state_machine_tot_value",
"lowest_power_consumption_idle_state_value_per_hours",
"lowest_power_consumption_machine_id",
"lowest_power_consumption_wk_state_machine_cost",
"lowest_power_consumption_wk_state_machine_id",
"lowest_power_consumption_wk_state_machine_tot_value",
"lowest_power_consumption_wk_state_machine_value_per_hour",
"machine_usage_trend",
"machine_utilization_rate",
"most_used_machine_id",
"most_used_machine_id_past",
"most_used_machine_time",
"most_used_machine_time_past",
"power_cost_per_hour",
"shortest_alarm_time",
"shortest_alarm_time_machine_id",
"tot_alarm_time",
"tot_connected_machine",
"tot_idle_time",
"tot_idle_time_past",
"tot_machine_used_percentage_of_period",
"tot_power_consumption",
"tot_power_cost_per_idle_hours",
"tot_power_cost_per_wk_hours",
"tot_wk_time",
"tot_wk_time_past"];*/

//TO PRINT ENTIRE TABLE kpi = "documentation";


(async () => {
    const kpi = "documentation";
    const toPrint = await KPI_Table_Interface(kpi, '2023-05-02', '2023-05-09', 5, null, null);
    console.log(toPrint);
    return;
})();